### ISSUE TITLE
Link to Youtube Playlist in README.md is incorrect.

### ISSUE THREAD

**Issue by MusaToTheMoon** [yegor256/osbp#15]
The current link in README.md for the youtube playlist takes to the Project Management playlist on your channel. 

The corrected link is: [https://www.youtube.com/watch?v=jYeZuaLt7nI&list=PLaIsQH4uc08zjutyoBOtoa6fnxzrCQK2Q&index=1&ab_channel=YegorBugayenko](https://www.youtube.com/watch?v=jYeZuaLt7nI&list=PLaIsQH4uc08zjutyoBOtoa6fnxzrCQK2Q&index=1&ab_channel=YegorBugayenko)

**Comment by yegor256** [comment]
@MusaToTheMoon fixed in 3863fa6 thanks!
